### ISSUE TITLE
vue-iclient-mapboxgl三维场景问题

### ISSUE THREAD

**Issue by ashur816** [SuperMap/vue-iclient#14]
``` Vue.use(VueiClient, { cesiumPath: './Build/Cesium/Cesium.js' }); ```

1、按照这个方法，Cesium整个包都加进去了，但是还是报错 ``` Unknown custom element: <vc-viewer> ```

![image](https://user-images.githubusercontent.com/16848641/90849957-1d5c8b00-e3a3-11ea-907f-d0acee2e13da.png)
2、我看这个里面已经有了，还需要指定外部路径么？

3、求个可行的集成方法

**Comment by songyumeng** [comment]
https://www.npmjs.com/package/@supermap/vue-iclient3d-webgl
