### ISSUE TITLE
提个BUG，在ElementUI的项目中会引起冲突

### ISSUE THREAD

**Issue by ZedLiu** [SuperMap/vue-iclient#15]
ElementUI的message使用的是this.$message({})，超图里面用的是Ant-design，ant的message也是叫this.$message，这样的话会导致之前项目中用elmentUI的message方法全部都报错了，因为他俩的用法不太一样，建议优化一下。

超图的代码是在src/mapboxgl/index.ts中，大概59行：Vue.prototype.$message = message;

ElementUI的官方文档说明：
Element 为 Vue.prototype 添加了全局方法 $message。因此在 vue instance 中可以采用本页面中的方式调用 Message。

**Comment by edte** [comment]
原来是这个原因，怪不得我用elementui后，又引入antd后this.$message全报错了
