### ISSUE TITLE
完整引入后污染了全局样式？

### ISSUE THREAD

**Issue by zhupengsheng** [SuperMap/vue-iclient#36]
import Vue from 'vue';
import VueiClient from '@supermap/vue-iclient-mapboxgl';

Vue.use(VueiClient);

**Comment by qazwsx12345edc** [comment]
引入之后部分页面样式受到了影响，如何解决？

**Comment by songyumeng** [comment]
谢谢您报的issue。
能否提供demo以便我们更方便快速的定位和解决问题。

**Comment by zhupengsheng** [comment]
This is an automatic reply confirming that your e-mail was received. Thank you!

**Comment by zhupengsheng** [comment]
This is an automatic reply confirming that your e-mail was received. Thank you!

**Comment by zhupengsheng** [comment]
This is an automatic reply confirming that your e-mail was received. Thank you!

**Comment by zhupengsheng** [comment]
This is an automatic reply confirming that your e-mail was received. Thank you!
