### ISSUE TITLE
安装vue-iclient使用echarts报错

### ISSUE THREAD

**Issue by ggglmc** [SuperMap/vue-iclient#37]
![image](https://user-images.githubusercontent.com/31680174/172778014-78ced741-33cd-428b-9e14-bec723436a7c.png)
版本"@supermap/vue-iclient-mapboxgl": "^11.0.0-beta"
![image](https://user-images.githubusercontent.com/31680174/172778198-b1fb8401-2a37-47f1-875b-9cecdd011c05.png)
使用情况
打断点发现echart是元素，不是echart
node版本14.19.1，@vue/cli 5.0.4
echartoption就是你们超图里面的例子
https://iclient.supermap.io/examples/component/editor.html#components_echarts_vue

**Comment by songyumeng** [comment]
谢谢您提的issue。这个问题已修复，请安装@supermap/vue-iclient-mapboxgl@11.0.0。
