### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by sendreams** [SuperMap/vue-iclient#4]
1、目前的demo页面充斥了太多东西，所有功能都往一个页面上堆，显然不利于新手学习。建议做多些页面，每个页面只介绍一个组件或一个功能的用法。
2、不建议一上来就对接超图在线地图，虽然开发人员可快速看到效果，不过从目前的demo看在线地图的配置和本地地图的配置不一样，不方便用户快速上手。
3、不建议通过mapID去区分在线和本地地图，通过options的参数控制更好些，这样开发人员只需要关注一个参数对象，不用去考虑额外的参数对象比如mapID等，把相关参数放在一起，而不是构建多个对象，分别用之，这样会加大用户的学习成本。
4、提供属性信息微件，便于用户查看或修改属性数据。

**Comment by acidgis** [comment]
1、预计9月会将demo拆分出来形成webgis组件库独立的页面和相关文档
2、逐步增加互联网地图的范例
3、mapid的设计主要是为简化对iportal产品发布地图的访问
4、属性是针对地图还是叠加图层，亦或其它？

**Comment by sendreams** [comment]
@acidgis 类似idesktop的对象属性窗口，便于修改属性信息。这个控件可设计的灵活一些，用于适配用户自定义的rest接口，而不是都跟超图的既有接口绑定死，比如可设置changUrl，让用户自行配置变更。开发者很可能是选中一个对象，自行查询对象关联业务表的属性信息，之后通过属性窗口显示，如果用户修改了属性值，再通过自定义的接口更新业务表。
