### ISSUE TITLE
vue2.0引入vue-iclient3d-webgl启动报错

### ISSUE THREAD

**Issue by 1049388229** [SuperMap/vue-iclient#46]
vue2.0引入vue-iclient3d-webgl启动报错，我用的是现在的若依框架，在main.js引入vue-iclient3d-webgl后启动直接报错，报错信息如下：
 ERROR  Failed to compile with 1 error                                                                                                                                      下午5:20:21

 error  in ./node_modules/@supermap/vue-iclient3d-webgl/dist/styles/images/cur/draw.cur

Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/@vue/cli-service/node_modules/postcss-loader/src??ref--6-oneOf-3-2!./node_modules/@supermap/vue-iclient3d-webgl/dist/styles/vue-iclient3d-webgl.min.css 12:36-68
 @ ./node_modules/@supermap/vue-iclient3d-webgl/dist/styles/vue-iclient3d-webgl.min.css
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.36.180:8099&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by songyumeng** [comment]
谢谢您的issue，这是一个[SuperMap/iClient3D-for-WebGL](https://github.com/SuperMap/iClient3D-for-WebGL)的问题，麻烦请您去[issue](https://github.com/SuperMap/iClient3D-for-WebGL/issues)提issue，方便我们三维同事定位跟踪。
