### ISSUE TITLE
动态加载图层

### ISSUE THREAD

**Issue by sendreams** [SuperMap/vue-iclient#5]
我想在地图上动态加载图层，该如何操作呢？

`  axios
        .get(this.host + '/iserver/services/pipeComponent/restjsr/query/maps/zp.json')
        .then(response => {
          var rasteLayerOptions = {
            name: 'GD',
            opacity: 0.8,
            visible: true,
            tiles: [this.host + '/iserver/services/map-NWJG/rest/maps/PD_GD/zxyTileImage.png?z={z}&x={x}&y={y}'],
            mapUrl: this.host + '/iserver/services/map-NWJG/rest/maps/PD_GD'
          };
          var lyr = new RasterTileLayerViewModel(map, rasteLayerOptions);
          // this.info = response.data;
        });`

我尝试新建RasterTileLayerViewModel对象，不过没用。

**Comment by sendreams** [comment]
我有两幅地图，是能正常叠加在一起的，但是使用以下代码缺始终不行，

> <sm-web-map :mapOptions='mapOptions' :style="{height:'100vh'}" @load="mapLoaded">
      <sm-pan></sm-pan>
      <sm-zoom :show-zoom-slider="false"></sm-zoom>
      <sm-layer-list position="top-right" />
      <sm-mini-map position="bottom-right"></sm-mini-map>
      <sm-measure position="top-right"></sm-measure>
      <sm-raster-tile-layer v-bind="rasteLayerOptions"></sm-raster-tile-layer>
    </sm-web-map>

> export default {
  data() {
    var host = window.isLocal ? window.server : 'http://211.136.105.71:8090';  //http://support.supermap.com.cn:8090

    return {
      host: host,
      layerStyles: {
        line: new smcomponents.commontypes.LineStyle({ 'line-width': 3, 'line-color': '#3fb1e3' }),
        circle: new smcomponents.commontypes.CircleStyle({ 'circle-color': '#3fb1e3', 'circle-radius': 6 }),
        fill: new smcomponents.commontypes.FillStyle({ 'fill-color': '#3fb1e3', 'fill-opacity': 0.8 })
      },
      styleObject: {
        width: '600px'
      },
      rasteLayerOptions: {
        layerId: '周浦管线',
        name: 'ZhouPuGX',
        // tileSize: 256,
        opacity: 0.8,
        visible: true,
        // tiles: [host + '/iserver/services/map-NWJG/rest/maps/ZhouPuGX/zxyTileImage.png?z={z}&x={x}&y={y}'],
        mapUrl: host + '/iserver/services/map-NWJG/rest/maps/ZhouPuGX'
      },
      restDataQuery: [
        new smcomponents.commontypes.RestDataParameter({
          url: host + '/iserver/services/data-world/rest/data',
          attributeFilter: "NAME='Huang He'",
          dataName: ['World:Countries']
        })
      ],
      layerSourceNames: ['pd'],
      mapOptions: {
        container: 'map', // container id
        style: {
          version: 8,
          sources: {
            '浦东底图': {
              type: 'raster',
              tiles: [
                host + '/iserver/services/map-pd/rest/maps/BaseMap/zxyTileImage.png?z={z}&x={x}&y={y}'
              ],
              tileSize: 256
            }
          },
          layers: [
            {
              id: 'simple-tiles',
              type: 'raster',
              source: '浦东底图',
              minzoom: 0,
              maxzoom: 20
            }
          ]
        },
        center: [120.143, 30.236],
        zoom: 9
      },
    };
  },

只能看到底图，不能看到上面的管线，从网络我有两幅地图，是能正常叠加在一起的，但是使用以下代码缺始终不行，

> <sm-web-map :mapOptions='mapOptions' :style="{height:'100vh'}" @load="mapLoaded">
      <sm-pan></sm-pan>
      <sm-zoom :show-zoom-slider="false"></sm-zoom>
      <sm-layer-list position="top-right" />
      <sm-mini-map position="bottom-right"></sm-mini-map>
      <sm-measure position="top-right"></sm-measure>
      <sm-raster-tile-layer v-bind="rasteLayerOptions"></sm-raster-tile-layer>
    </sm-web-map>

> export default {
  data() {
    var host = window.isLocal ? window.server : 'http://211.136.105.71:8090';  //http://support.supermap.com.cn:8090

    return {
      host: host,
      layerStyles: {
        line: new smcomponents.commontypes.LineStyle({ 'line-width': 3, 'line-color': '#3fb1e3' }),
        circle: new smcomponents.commontypes.CircleStyle({ 'circle-color': '#3fb1e3', 'circle-radius': 6 }),
        fill: new smcomponents.commontypes.FillStyle({ 'fill-color': '#3fb1e3', 'fill-opacity': 0.8 })
      },
      styleObject: {
        width: '600px'
      },
      rasteLayerOptions: {
        layerId: '周浦管线',
        name: 'ZhouPuGX',
        // tileSize: 256,
        opacity: 0.8,
        visible: true,
        // tiles: [host + '/iserver/services/map-NWJG/rest/maps/ZhouPuGX/zxyTileImage.png?z={z}&x={x}&y={y}'],
        mapUrl: host + '/iserver/services/map-NWJG/rest/maps/ZhouPuGX'
      },
      restDataQuery: [
        new smcomponents.commontypes.RestDataParameter({
          url: host + '/iserver/services/data-world/rest/data',
          attributeFilter: "NAME='Huang He'",
          dataName: ['World:Countries']
        })
      ],
      layerSourceNames: ['pd'],
      mapOptions: {
        container: 'map', // container id
        style: {
          version: 8,
          sources: {
            '浦东底图': {
              type: 'raster',
              tiles: [
                host + '/iserver/services/map-pd/rest/maps/BaseMap/zxyTileImage.png?z={z}&x={x}&y={y}'
              ],
              tileSize: 256
            }
          },
          layers: [
            {
              id: 'simple-tiles',
              type: 'raster',
              source: '浦东底图',
              minzoom: 0,
              maxzoom: 20
            }
          ]
        },
        center: [120.143, 30.236],
        zoom: 9
      },
    };
  },

只能看到底图，不能看到上面的管线，从网络访问情况看，会产生类似这样的请求
http://211.136.105.71:8090/iserver/services/map-NWJG/rest/maps/ZhouPuGX/tileimage.png?scale=0.00005538327991427593&x=27449&y=13402&width=256&height=256&transparent=true&origin={"x":-20037508.3427892,"y":20037508.3427892}

origin不知从哪里来的，
xy值非常大，不知为何？

代码中的两幅图用classic开发方式是能正常查看的。

**Comment by sendreams** [comment]
> <sm-web-map :mapOptions='mapOptions' :style="{height:'100vh'}" @load="mapLoaded">
      <sm-pan></sm-pan>
      <sm-zoom :show-zoom-slider="false"></sm-zoom>
      <sm-layer-list position="top-right" />
      <sm-mini-map position="bottom-right"></sm-mini-map>
      <sm-measure position="top-right"></sm-measure>
      <sm-raster-tile-layer v-bind="rasteLayerOptions"></sm-raster-tile-layer>
    </sm-web-map>

**Comment by sendreams** [comment]
发现有些图层无法呈现，如下面这幅地图
'http://211.136.105.71:8090/iserver/services/map-NWJG/rest/maps/PuDongGX'
我使用在线示例修改代码也是不行。

'http://211.136.105.71:8090/iserver/services/map-pd/rest/maps/BaseMap' 这副地图就可以。
这是什么原因呢？
还请核实。

**Comment by sendreams** [comment]
没人吗

**Comment by acidgis** [comment]
正在确认此问题，感谢您的反馈

**Comment by sendreams** [comment]
> 正在确认此问题，感谢您的反馈

还没确认好？

**Comment by liqian7** [comment]
感谢你的提问。

“只能看到底图，不能看到上面的管线” 原因是:
因为你的数据是 4326（WGS84） 坐标系， SuperMap iServer 的 **zxyTileImage** 资源会将坐标系动态投影成 3857（web 墨卡托）。但是我们测试发现 “ZhouPuGX“”这幅地图的zxyTileImage并不会出图（原因不详。可能是数据不支持动态投影）

当前情况，可以考虑直接加载 4326 地图， 可以参考 iClient [底图 _WGS84 范例](http://iclient.supermap.io/examples/mapboxgl/editor.html#01_tiledMapLayer_4326)

解决办法为（详细请参考范例）：
1   tiles 参数应为 **`tiles: ['http://211.136.105.71:8090/iserver/services/map-pd/rest/maps/BaseMap']`** 
2   与 tiles 同级添加 rasterSource 参数: **`rasterSource: "iserver"`**
3   mapOptions 设置 crs 参数 :  **`crs: "EPSG:4326"`**
结果如图：
![image](https://user-images.githubusercontent.com/35757238/63916346-ce6b6680-ca6a-11e9-90c4-1471325522bf.png)

**Comment by sendreams** [comment]
@liqian7 谢谢你的解答。另外，我的主要问题是：如何动态加载图层。
假设我后台定义了一些图层信息，前台通过ajax请求获取这些图层信息，在客户端动态创建图层。
目前的各种示例都是定义好了option然后通过vue加载，能不能提供些动态加载图层的示例？谢谢。

**Comment by liqian7** [comment]
@sendreams
请问你需要动态加载什么类型的图层呢？
目前我们支持 **animateMarkerLayer/clusterLayer/geoJsonLayer** 动态加载， 其它图层还在持续完善中

以 GeoJSON 图层为例：

``` vue
<sm-web-map :map-options="mapOptions">
  <sm-geojson-layer :layer-style="layerStyle" :data="data" ></sm-geojson-layer>
</sm-web-map>
```

结果如图：
![image](https://user-images.githubusercontent.com/35757238/64312304-fcf0c080-cfd9-11e9-90e7-8bcfaa507077.png)

**Comment by sendreams** [comment]
@liqian7 这不是动态加载吧，代码写死的。我的意思是程序启动后，根据业务需要，动态添加图层到地图，当然也可能动态删除图层。
以前就是map.addLayer(xxx)，现在换成vue了，不懂怎么调用。

**Comment by liqian7** [comment]
动态加载图层，有下面几种方法

1 事先预留组件位置，再动态改变对象的值
> @sendreams
> 请问你需要动态加载什么类型的图层呢？
> 目前我们支持 **animateMarkerLayer/clusterLayer/geoJsonLayer** 动态加载， 其它图层还在持续完善中
> 
> 以 GeoJSON 图层为例：
> 
> ```
> <sm-web-map :map-options="mapOptions">
>   <sm-geojson-layer :layer-style="layerStyle" :data="data" ></sm-geojson-layer>
> </sm-web-map>
> ```
> 
> 结果如图：
> ![image](https://user-images.githubusercontent.com/35757238/64312304-fcf0c080-cfd9-11e9-90e7-8bcfaa507077.png)

2 获得 Map 之后，（在你的业务需要时）动态创建组件，再 $mount 进 Map 节点
``` js
const GeojsonLayerExtend = Vue.extend(GeojsonLayer);
const GeojsonLayerInstance = new GeojsonLayerExtend({
  propsData: {
    data: result,
    layerStyle: this.layerStyle[type],
    layerId
  }
});
let component = GeojsonLayerInstance.$mount();
this.map.getContainer().appendChild(component.$el);
```

**PS:  以上两种方式，与 Vue 中的动态组件是一致的，若有疑问，请自行参阅 Vue 官方文档或谷歌搜索相关技术博客**

3 WebMap 提供 Map 加载完成回调事件，你可以在回调中拿到 Map 干你任何想干的事。

参考 Vue-iClient 组件文档 [Event-load](https://supermap.github.io/vue-iclient/zh/api/web-map/map.html#events)
``` vue
<sm-web-map @load="load">

load(e) {
  let map = e.map
}
```

**Comment by sendreams** [comment]
@liqian7 其实我就是想拿到map对象，谢谢。
