### ISSUE TITLE
加入"@supermap/iclient-leaflet": "^11.1.1",工程启动报错

### ISSUE THREAD

**Issue by mingxinyiriyi** [SuperMap/vue-iclient#63]
加入"@supermap/iclient-leaflet": "^11.1.1",工程启动报错，错误如下图，包已经都下载了在node_modules里面存在：
98% after emitting CopyPlugin                                                                                                                               
 ERROR  Failed to compile with 2 errors                                                                                                        

These relative modules were not found:

* ./config.js in ./node_modules/@supermap/iclient-leaflet/node_modules/flatgeobuf/lib/mjs/packedrtree.js
* ../logger.js in ./node_modules/@supermap/iclient-leaflet/node_modules/flatgeobuf/lib/mjs/generic/featurecollection.js

**Comment by songyumeng** [comment]
参考https://github.com/SuperMap/iClient-JavaScript/issues/447
后续版本会处理该问题
