### ISSUE TITLE
项目初次启动不起来

### ISSUE THREAD

**Issue by Titans1001** [SuperMap/vue-iclient#7]
n /project/supermap/vue-iclient-master/src/mapboxgl/web-map/WebMap.vue.ts

[tsl] ERROR in /project/supermap/vue-iclient-master/src/mapboxgl/web-map/WebMap.vue.ts(357,12)
      TS2339: Property '$message' does not exist on type 'SmWebMap'.
下载最新版本，执行命令npm run dev后控制台报错：
 error  in /project/supermap/vue-iclient-master/src/mapboxgl/web-map/WebMap.vue.ts

[tsl] ERROR in /project/supermap/vue-iclient-master/src/mapboxgl/web-map/WebMap.vue.ts(369,12)
      TS2339: Property '$message' does not exist on type 'SmWebMap'.

 error  in /project/supermap/vue-iclient-master/src/mapboxgl/web-map/WebMap.vue.ts

[tsl] ERROR in /project/supermap/vue-iclient-master/src/mapboxgl/web-map/WebMap.vue.ts(369,32)
      TS2339: Property '$t' does not exist on type 'SmWebMap'.

 error  in /project/supermap/vue-iclient-master/src/mapboxgl/web-map/layer/animate-marker/AnimateMarkerLayer.vue.ts

[tsl] ERROR in /project/supermap/vue-iclient-master/src/mapboxgl/web-map/layer/animate-marker/AnimateMarkerLayer.vue.ts(19,2)
      TS2769: No overload matches this call.

**Comment by Jame-Chen** [comment]
![image](https://user-images.githubusercontent.com/24774525/76593012-fbc3c180-652f-11ea-8395-8fe92bbb8d33.png)
我的也报错，但确定这些包都是有的

**Comment by bailihua93** [comment]
原始的项目不确定哪里出问题了， 直接npm run docs:dev 可以看开发文档
